---
filebeat_version: 7.9.1

wazuh_template_branch: v4.0.3

filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

filebeat_module_package_url: https://packages.wazuh.com/4.x/filebeat
filebeat_module_package_name: wazuh-filebeat-0.1.tar.gz
filebeat_module_package_path: /tmp/
filebeat_module_destination: /usr/share/filebeat/module
filebeat_module_folder: /usr/share/filebeat/module/wazuh
elasticsearch_security_user: admin
elasticsearch_security_password: changeme
# Security plugin
filebeat_security: true
filebeat_ssl_dir: /etc/pki/filebeat

# Local path to store the generated certificates (OpenDistro security plugin)
local_certs_path: ./opendistro/certificates

elasticrepo:
  apt: 'https://artifacts.elastic.co/packages/oss-7.x/apt'
  yum: 'https://artifacts.elastic.co/packages/oss-7.x/yum'
  gpg: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  key_id: '46095ACC8548582C1A2699A9D27D666CD88E42B4'
