---
wazuh_filebeat_version: 7.10.2

wazuh_template_branch: v4.14.4

wazuh_filebeat_node_name: node-1

wazuh_filebeat_output_indexer_hosts:
  - "localhost"

wazuh_filebeat_module_package_name: wazuh-filebeat-0.5.tar.gz
wazuh_filebeat_module_package_path: /tmp/
wazuh_filebeat_module_destination: /usr/share/filebeat/module
wazuh_filebeat_module_folder: /usr/share/filebeat/module/wazuh
wazuh_indexer_security_user: admin
wazuh_indexer_security_password: changeme
# Security plugin
wazuh_filebeat_security: true
wazuh_filebeat_ssl_dir: /etc/pki/filebeat

# Local path to store the generated certificates (Opensearch security plugin)
wazuh_local_certs_path: "{{ playbook_dir }}/indexer/certificates"
