---
- name: Restart wazuh-manager
  ansible.builtin.service:
    name: wazuh-manager
    state: restarted
    enabled: true

- name: Restart wazuh-api
  ansible.builtin.service:
    name: wazuh-api
    state: restarted
    enabled: true
