---
- name: Restart wazuh-agent
  ansible.builtin.service:
    name: wazuh-agent
    state: restarted
    enabled: true
  become: true

- name: Windows | Restart Wazuh Agent
  ansible.windows.win_service:
    name: WazuhSvc
    start_mode: auto
    state: restarted

- name: MacOS | Restart Wazuh Agent
  ansible.builtin.command: /Library/Ossec/bin/wazuh-control restart
  changed_when: false
