---
- name: Configure Filebeat
  tags:
    - configure
  block:
    - name: Copy Filebeat configuration.
      ansible.builtin.template:
        src: filebeat.yml.j2
        dest: "/etc/filebeat/filebeat.yml"
        owner: root
        group: root
        mode: "0400"
      notify: Restart filebeat

    - name: Fetch latest Wazuh alerts template
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/wazuh/wazuh/{{ wazuh_template_branch }}/extensions/elasticsearch/7.x/wazuh-template.json
        dest: "/etc/filebeat/wazuh-template.json"
        owner: root
        group: root
        mode: "0400"
      notify: Restart filebeat
