---
# Wazuh Manager
  - name: Check if Wazuh Manager is already installed
    stat:
      path: "{{ wazuh_dir }}/bin/ossec-control"
    register: wazuh_ossec_control

  - name: Installing Wazuh Manager from sources
    block:
      - name: Install dependencies to build Wazuh packages
        package:
          name:
            - make
            - gcc
            - automake
            - autoconf
            - libtool
            - tar
          state: present

      - name: Removing old files
        file:
          path: "/tmp/{{ wazuh_manager_sources_installation.branch }}.tar.gz"
          state: absent

      - name: Removing old folders
        file:
          path: "/tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}"
          state: absent

      - name: Installing policycoreutils-python (RedHat families)
        package:
          name:
            - policycoreutils-python
        when:
          - ansible_os_family|lower == "redhat"

      - name: Installing policycoreutils-python-utils (Debian families)
        package:
          name:
            - libc6-dev
            - curl
            - policycoreutils
        when:
          - ansible_os_family|lower == "debian"

      - name: Remove old repository folder
        file:
          path: /tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}
          state: absent

      - name: Download required packages from github.com/wazuh/wazuh
        get_url:
          url: "https://github.com/wazuh/wazuh/archive/{{ wazuh_manager_sources_installation.branch }}.tar.gz"
          dest: "/tmp/{{ wazuh_manager_sources_installation.branch }}.tar.gz"
        delegate_to: "{{ inventory_hostname }}"

      - name: Create folder to extract Wazuh branch
        file:
          path: "/tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}"
          owner: root
          group: root
          mode: 0644
          state: directory

    # When downloading "v3.11.0" extracted folder name is 3.11.0.

    # Explicitly creating the folder with proper naming and striping first level in .tar.gz file

      - name: Extract downloaded Wazuh branch from Github # Using shell instead of unarchive due to that module not working properlyh with --strip
        command: >-
          tar -xzvf /tmp/{{ wazuh_manager_sources_installation.branch }}.tar.gz
          --strip 1
          --directory /tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}
        register: wazuh_untar
        changed_when: wazuh_untar.rc ==0
        args:
          warn: false

      - name: Clean remaining files from others builds
        command: "make -C src {{ item }}"
        args:
          chdir: "/tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}/src/"
        with_items:
          - "clean"
          - "clean-deps"
        register: clean_result
        changed_when: clean_result.rc == 0
        failed_when: false

      - name: Render the "preloaded-vars.conf" file
        template:
          src: "templates/preloaded_vars_manager.conf.j2"
          dest: "/tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}/etc/preloaded-vars.conf"
          owner: root
          group: root
          mode: 0644

      - name: Executing "install.sh" script to build and install the Wazuh Manager
        shell: ./install.sh > /tmp/build_wazuh_manager_log.txt
        register: installation_result
        changed_when: installation_result == 0
        args:
          chdir: "/tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}"

      - name: Cleanup downloaded files
        file:
          path: "/tmp/{{ wazuh_manager_sources_installation.branch }}.tar.gz"
          state: absent

      - name: Cleanup created folders
        file:
          path: "/tmp/wazuh-{{ wazuh_manager_sources_installation.branch }}"
          state: absent

    when:
      - not wazuh_ossec_control.stat.exists
      - wazuh_manager_sources_installation.enabled
    tags:
      - manager
