---
- name: RedHat/CentOS/Fedora | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: Wazuh repository
    baseurl: "{{ wazuh_manager_config.repo.yum }}"
    gpgkey: "{{ wazuh_manager_config.repo.gpg }}"
    gpgcheck: true
  changed_when: false
  when:
    - not wazuh_manager_sources_installation.enabled
    - not wazuh_custom_packages_installation_manager_enabled

- name: RedHat/CentOS/Fedora | Install openscap
  package: name={{ item }} state=present
  with_items:
    - openscap-scanner
  register: wazuh_manager_openscp_packages_installed
  until: wazuh_manager_openscp_packages_installed is succeeded
  tags:
    - init
  when: not (ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA") and
        not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")

- name: RedHat/CentOS/Fedora | Install OpenJDK 1.8
  yum: name=java-1.8.0-openjdk state=present
  when:
    - wazuh_manager_config.cis_cat.disable == 'no'
    - wazuh_manager_config.cis_cat.install_java == 'yes'
  tags:
    - init

- name: Set Distribution CIS filename for RHEL7/CentOS-7
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when:
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: Set Distribution CIS filename for RHEL7/CentOS-7 (Amazon)
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when:
    - ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"

- name: Install dependencies to build from sources
  yum:
    name: ['make', 'gcc', 'automake', 'autoconf', 'libtool', 'tar', 'openssl-devel', 'gcc-c++']
    state: present
  when: wazuh_manager_sources_installation.enabled

- name: CentOS/RedHat/Amazon | Install wazuh-manager
  package:
    name: "wazuh-manager-{{ wazuh_manager_version }}"
    state: "{{ wazuh_manager_package_state }}"
  register: wazuh_manager_main_packages_installed
  until: wazuh_manager_main_packages_installed is succeeded
  when:
    - ansible_os_family|lower == "redhat"
    - not wazuh_manager_sources_installation.enabled
    - not wazuh_custom_packages_installation_manager_enabled
  tags:
    - init

- include_tasks: "../tasks/installation_from_sources.yml"
  when:
    - wazuh_manager_sources_installation.enabled

- include_tasks: "../tasks/installation_from_custom_packages.yml"
  when:
    - wazuh_custom_packages_installation_manager_enabled
