---

elasticsearch_http_port: 9200
elasticsearch_network_host: 127.0.0.1
elasticsearch_reachable_host: 127.0.0.1
elasticsearch_jvm_xms: null
elastic_stack_version: 7.9.3
elasticsearch_lower_disk_requirements: false
elasticsearch_path_repo: []

elasticrepo:
  apt: 'https://artifacts.elastic.co/packages/7.x/apt'
  yum: 'https://artifacts.elastic.co/packages/7.x/yum'
  gpg: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  key_id: '46095ACC8548582C1A2699A9D27D666CD88E42B4'

# Cluster Settings
single_node: true
elasticsearch_cluster_name: wazuh
elasticsearch_node_name: node-1
elasticsearch_bootstrap_node: false
elasticsearch_node_master: false
elasticsearch_cluster_nodes:
  - 127.0.0.1
elasticsearch_discovery_nodes:
  - 127.0.0.1
elasticsearch_node_data: true
elasticsearch_node_ingest: true

# X-Pack Security
elasticsearch_xpack_security: false
elasticsearch_xpack_security_password: elastic_pass

node_certs_generator: false
node_certs_source: /usr/share/elasticsearch
node_certs_destination: /etc/elasticsearch/certs

# CA generation
master_certs_path: "{{ playbook_dir }}/es_certs"
generate_CA: true
ca_key_name: ""
ca_cert_name: ""
ca_password: ""
