---
- name: CentOS | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: CentOS-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/el/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'CentOS'

- name: Fedora | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: Fedora-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/fc/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'Fedora'

- name: RedHat | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: CentOS-$releasever - Wazuh
    baseurl: https://packages.wazuh.com/yum/rhel/$releasever/$basearch
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes
  when: ansible_distribution == 'RedHat'

- name: Set Distribution CIS filename for RHEL5
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- name: Set Distribution CIS filename for RHEL6
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Set Distribution CIS filename for RHEL7
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: RedHat/CentOS/RedHat | Install openscap
  package: name=openscap-scanner state=present
  tags:
    - init
