---
- name: Include Repository Variables
  ansible.builtin.include_vars: ../../vars/repo_vars.yml

- name: Include Production Repository Variables
  ansible.builtin.include_vars: ../../vars/repo.yml
  when: packages_repository == 'production'

- name: Include Pre-Release Repository Variables
  ansible.builtin.include_vars: ../../vars/repo_pre-release.yml
  when: packages_repository == 'pre-release'

- name: Include Staging Repository Variables
  ansible.builtin.include_vars: ../../vars/repo_staging.yml
  when: packages_repository == 'staging'

- name: Run Local Actions
  ansible.builtin.import_tasks: local_actions.yml
  when:
    - wazuh_generate_certs

- name: Configure Wazuh Indexer
  when: wazuh_perform_installation
  block:
    - name: RedHat/Centos | Install Wazuh Indexer
      ansible.builtin.import_tasks: RedHat.yml
      when: ansible_os_family == 'RedHat'

    - name: Debian/Ubuntu | Install Wazuh Indexer
      ansible.builtin.import_tasks: Debian.yml
      when: ansible_os_family == 'Debian'

    - name: Remove performance analyzer plugin from Wazuh indexer
      ansible.builtin.command: ./opensearch-plugin remove opensearch-performance-analyzer
      ignore_errors: true
      args:
        chdir: /usr/share/wazuh-indexer/bin/
      register: remove_opensearch_performance_analyzer
      failed_when:
        - remove_opensearch_performance_analyzer.rc != 0
        - '"not found" not in remove_opensearch_performance_analyzer.stderr'
      changed_when: "remove_opensearch_performance_analyzer.rc == 0"
      become: true

    - name: Remove Opensearch configuration file
      ansible.builtin.file:
        path: "{{ wazuh_indexer_conf_path }}/opensearch.yml"
        state: absent
      tags: install

    - name: Copy Opensearch Configuration File
      ansible.builtin.template:
        src: "templates/opensearch.yml.j2"
        dest: "{{ wazuh_indexer_conf_path }}/opensearch.yml"
        owner: root
        group: wazuh-indexer
        mode: "0640"
        force: true
      tags: install

    - name: Run Security Actions
      ansible.builtin.include_tasks: security_actions.yml
      tags:
        - security

    - name: Configure Wazuh indexer JVM memmory.
      ansible.builtin.template:
        src: "templates/jvm.options.j2"
        dest: "{{ wazuh_indexer_conf_path }}/jvm.options"
        owner: root
        group: wazuh-indexer
        mode: "0644"
        force: true
      notify: Restart wazuh-indexer
      tags: install

    - name: Ensure extra time for Wazuh indexer to start on reboots
      ansible.builtin.lineinfile:
        path: /usr/lib/systemd/system/wazuh-indexer.service
        regexp: '^TimeoutStartSec='
        line: "TimeoutStartSec={{ wazuh_indexer_start_timeout }}"
      become: true
      tags: configure

    - name: Index files to remove
      ansible.builtin.find:
        paths: "{{ wazuh_indexer_index_path }}"
        patterns: "*"
      register: files_to_delete

    - name: Remove Index Files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Ensure Wazuh indexer started and enabled
      ansible.builtin.service:
        name: wazuh-indexer
        enabled: true
        state: started

    - name: Wait for Wazuh indexer API
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname if not wazuh_single_node else wazuh_indexer_network_host }}:{{ wazuh_indexer_http_port }}/_cat/health/"
        user: "admin" # Default Indexer user is always "admin"
        password: "{{ wazuh_indexer_admin_password }}"
        validate_certs: false
        status_code: 200,401
        return_content: true
        timeout: 4
      register: _result
      until:
        - _result is defined
        - '"green" in _result.content or ( "yellow" in _result.content and wazuh_single_node )'
      retries: 24
      delay: 5
      tags: debug
      when:
        - hostvars[inventory_hostname]['private_ip'] is not defined or not hostvars[inventory_hostname]['private_ip']

    - name: Wait for Wazuh indexer API (Private IP)
      ansible.builtin.uri:
        url: |
          https://{{ hostvars[inventory_hostname]['private_ip']
          if not wazuh_single_node else wazuh_indexer_network_host }}:{{ wazuh_indexer_http_port }}/_cat/health/
        user: "admin" # Default Indexer user is always "admin"
        password: "{{ wazuh_indexer_admin_password }}"
        validate_certs: false
        status_code: 200,401
        return_content: true
        timeout: 4
      register: _result
      until:
        - _result is defined
        - '"green" in _result.content or ( "yellow" in _result.content and wazuh_single_node )'
      retries: 24
      delay: 5
      tags: debug
      when:
        - hostvars[inventory_hostname]['private_ip'] is defined and hostvars[inventory_hostname]['private_ip']

    - name: Removing Red Hat Repository
      ansible.builtin.import_tasks: "RMRedHat.yml"
      when: ansible_os_family == "RedHat"

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
      notify: Restart wazuh-indexer
