---
- name: Install Wazuh Indexer
  tags:
    - install

  block:
    - name: RedHat/CentOS/Fedora | Add Wazuh indexer repo
      ansible.builtin.yum_repository:
        name: wazuh_repo
        description: Wazuh yum repository
        baseurl: "{{ wazuh_repo.yum }}"
        gpgkey: "{{ wazuh_repo.gpg }}"
        gpgcheck: true
      changed_when: false

    - name: Amazon Linux | Configure system settings
      when:
        - ansible_distribution == 'Amazon'
      block:
        - name: Install Amazon extras in Amazon Linux 2
          ansible.builtin.dnf:
            name: amazon-linux-extras
            state: present
            lock_timeout: 200
          when:
            - ansible_distribution == 'Amazon'
            - ansible_distribution_major_version == '2'

        - name: Configure vm.max_map_count
          ansible.builtin.lineinfile:
            line: "vm.max_map_count=262144"
            dest: "/etc/sysctl.conf"
            insertafter: EOF
            create: true
            owner: root
            group: root
            mode: "0644"
          become: true

        - name: Update vm.max_map_count
          ansible.builtin.command: sysctl -p
          changed_when: false
          become: true

    - name: RedHat/CentOS/Fedora | Install Indexer dependencies
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
        lock_timeout: 200
      vars:
        packages:
          - wget
          - unzip

    - name: Install Wazuh indexer
      ansible.builtin.package:
        name: wazuh-indexer-{{ wazuh_indexer_version }}
        state: present
      register: install
      tags: install
