---

########################################################
# Helper variables
private_ip: '{{ ansible_default_ipv4.address }}'

managers_hostvars: "{{ groups['managers'] | map('extract', hostvars)  | list }}"
elastic_hostvars: "{{ groups['elastic'] | map('extract', hostvars)  | list }}"

manager_addresses: "{{ managers_hostvars | map(attribute='private_ip') | list }}"
elastic_addresses: "{{ elastic_hostvars | map(attribute='private_ip') | list }}"

########################################################
# Versions
elastic_stack_version: 7.9.3
filebeat_version: 7.9.3

# Debian packages need the ${VERSION}-1
wazuh_manager_version: 4.0.4-1
wazuh_agent_version: 4.0.4-1

# Kibana role appends it automatically.
wazuh_version: 4.0.4