- name: Install Postfix and its dependencies
  package:
    name:
      - postfix
      - mailutils
      - libsasl2-2
      - ca-certificates
      - libsasl2-modules
    state: present
  become: true
  when: ansible_os_family == "Debian"
  tags:
    - init

- name: Install Postfix and its dependencies
  package:
    name:
      - postfix
      - s-nail
      - cyrus-sasl
      - cyrus-sasl-plain
    state: present
  become: true
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 5) or (ansible_os_family  == "RedHat" and ansible_distribution == "Amazon")
  tags:
    - init

- name: Configure Postfix
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      relayhost = [{{ wazuh_manager_external_email_smtp_server }}]:{{ wazuh_manager_external_email_smtp_port }}
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_sasl_security_options = noanonymous
      smtp_use_tls = {{ wazuh_manager_external_email_smtp_use_tls }}
    owner: root
    group: root
    mode: 0770
  become: true

- name: Configure postfix relay username and password
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0770
  become: true

- name: Create postfix database
  command: postmap /etc/postfix/sasl_passwd
  become: true

- name: Set file permissions for config file
  file:
    path: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  become: true

- name: Set file permissions for database
  file:
    path: /etc/postfix/sasl_passwd.db
    owner: root
    group: root
    mode: 0600
  become: true

- name: Restart postfix
  service:
    name: postfix
    state: restarted
    enabled: true
  become: true

- name: Sending test e-mail notifications via external smtp server
  community.general.mail:
    subject: Postfix Test
    body: Test email from postfix
    from: "{{ wazuh_manager_email_from }}"
    to: "{{ item }}"
  become: true
  loop: "{{ wazuh_manager_mailto }}"

