---
- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: restart logstash
  service: name=logstash state=restarted

- name: restart kibana
  service: name=kibana state=restarted
