---
# Cluster Settings
wazuh_indexer_version: 4.14.2

wazuh_single_node: false
wazuh_indexer_node_name: node-1
wazuh_indexer_cluster_name: wazuh
wazuh_indexer_network_host: '0.0.0.0'

wazuh_indexer_node_master: true
wazuh_indexer_node_data: true
wazuh_indexer_node_ingest: true
wazuh_indexer_start_timeout: 90

wazuh_indexer_cluster_nodes:
  - 127.0.0.1
wazuh_indexer_discovery_nodes:
  - 127.0.0.1

wazuh_local_certs_path: "{{ playbook_dir }}/indexer/certificates"

# Minimum master nodes in cluster, 2 for 3 nodes Wazuh indexer cluster
wazuh_minimum_master_nodes: 2

# Configure hostnames for Wazuh indexer nodes
# Example es1.example.com, es2.example.com
wazuh_domain_name: wazuh.com

wazuh_indexer_sec_plugin_conf_path: /etc/wazuh-indexer/opensearch-security
wazuh_indexer_sec_plugin_tools_path: /usr/share/wazuh-indexer/plugins/opensearch-security/tools
wazuh_indexer_conf_path: /etc/wazuh-indexer
wazuh_indexer_index_path: /var/lib/wazuh-indexer/

# Security password
wazuh_indexer_custom_user: ""
wazuh_indexer_custom_user_role: "admin"

# Set JVM memory limits
wazuh_indexer_jvm_xms: null

wazuh_indexer_http_port: 9200

wazuh_indexer_admin_password: changeme
wazuh_dashboard_password: changeme

# Deployment settings
wazuh_generate_certs: true
wazuh_perform_installation: true

wazuh_indexer_nolog_sensible: true
