---
# Cluster Settings
indexer_version: 4.4.4

single_node: false
indexer_node_name: node-1
indexer_cluster_name: wazuh
indexer_network_host: '0.0.0.0'

indexer_node_master: true
indexer_node_data: true
indexer_node_ingest: true
indexer_start_timeout: 90

indexer_cluster_nodes:
  - 127.0.0.1
indexer_discovery_nodes:
  - 127.0.0.1

local_certs_path: "{{ playbook_dir }}/indexer/certificates"

# Minimum master nodes in cluster, 2 for 3 nodes Wazuh indexer cluster
minimum_master_nodes: 2

# Configure hostnames for Wazuh indexer nodes
# Example es1.example.com, es2.example.com
domain_name: wazuh.com

indexer_sec_plugin_conf_path: /etc/wazuh-indexer/opensearch-security
indexer_sec_plugin_tools_path: /usr/share/wazuh-indexer/plugins/opensearch-security/tools
indexer_conf_path: /etc/wazuh-indexer
indexer_index_path: /var/lib/wazuh-indexer/

# Security password
indexer_custom_user: ""
indexer_custom_user_role: "admin"

# Set JVM memory limits
indexer_jvm_xms: null

indexer_http_port: 9200

indexer_admin_password: changeme
dashboard_password: changeme

# Deployment settings
generate_certs: true
perform_installation: true

indexer_nolog_sensible: true
