---
kibana_node_name: node-1

elasticsearch_http_port: "9200"
elasticsearch_network_host: "127.0.0.1"
kibana_server_host: "0.0.0.0"
kibana_server_port: "5601"
elastic_stack_version: 7.4.2
wazuh_version: 3.10.2
wazuh_app_url: https://packages.wazuh.com/wazuhapp/wazuhapp

# Xpack Security
kibana_xpack_security: false

elasticsearch_xpack_security_user: elastic
elasticsearch_xpack_security_password: elastic_pass

node_certs_generator: false
node_certs_source: /usr/share/elasticsearch
node_certs_destination: /etc/kibana/certs

# CA Generation
master_certs_path: /es_certs
generate_CA: true
ca_cert_name: ""

# Nodejs
node_js_repo_url: https://rpm.nodesource.com/setup_8.x
node_js_repo_type: rpm

# Build from sources
build_from_sources: false
wazuh_plugin_branch: 3.10-7.3