---

########################################################
# Helper variables
private_ip: '{{ ansible_default_ipv4.address }}'

managers_hostvars: "{{ groups['managers'] | map('extract', hostvars)  | list }}"
indexer_hostvars: "{{ groups['indexer'] | map('extract', hostvars)  | list }}"
dashboard_hostvars: "{{ groups['dashboard'] | map('extract', hostvars)  | list }}"

manager_addresses: "{{ managers_hostvars | map(attribute='private_ip') | list }}"
indexer_addresses: "{{ indexer_hostvars | map(attribute='private_ip') | list }}"
dashboard_addresses: "{{ dashboard_hostvars | map(attribute='private_ip') | list }}"

########################################################
# General Wazuh stack variables

# Wazuh indexer/dashboard
dashboard_security: true

dashboard_user: kibanaserver
indexer_security_user: admin

dashboard_password: changeme
indexer_security_password: changeme
indexer_admin_password: changeme

# All nodes are called by IP name
indexer_node_name: '{{ ansible_facts.hostname }}'
dashboard_node_name: '{{ ansible_facts.hostname }}'
filebeat_node_name: '{{ ansible_facts.hostname }}'

indexer_version: 4.5.0
filebeat_version: 7.10.2
wazuh_version: 4.5.0

# Debian packages need the ${VERSION}
wazuh_manager_version: 4.5.0
wazuh_agent_version: 4.5.0
