- block:

  - name: Copy the certificates from local to the Kibana instance
    copy:
      src: "{{ local_certs_path }}/certs/{{ item }}"
      dest: /usr/share/kibana
      mode: 0644
    with_items:
      - "root-ca.pem"
      - "{{ kibana_node_name }}_http.key"
      - "{{ kibana_node_name }}_http.pem"
  tags:
  - security
  when: install.changed