---

- name: Linux Debian (AMD64) | Download wazuh-agent package
  ansible.builtin.get_url:
    url: "{{ wazuh_agent_amd64_deb }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}_{{ ansible_facts.architecture }}.deb"
    mode: '0644'
  when:
    - ansible_facts.architecture == "x86_64"

- name: Linux Debian (ARM64) | Download wazuh-agent package
  ansible.builtin.get_url:
    url: "{{ wazuh_agent_arm64_deb }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}_{{ ansible_facts.architecture }}.deb"
    mode: '0644'
  when:
    - ansible_facts.architecture == "aarch64"
