---
- hosts: es_cluster
  roles:
    - role: ../roles/opendistro/opendistro-elasticsearch

  vars:
    instances:           # A certificate will be generated for every node using the name as CN.
      node1:
        name: node-1
        ip: <node-1 IP>
      node2:
        name: node-2
        ip: <node-2 IP>
      node3:
        name: node-3
        ip: <node-3 IP>

